### ISSUE TITLE
Define vertical spacing type styles

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#29]
As mentioned in #20, we should provide the spacing values for typography that is laid out as prose. This issue is for design to provide a table of the values for type styles that we can then add into code 👩‍💻

**Comment by joshblack** [comment]
cc @aagonzales do you want to chime in on how this will be applied in the default (product) theme?

**Comment by jeanservaas** [comment]
# Vertical Spacing

This issue really has three parts:

1. Vertical Spacing in the Carbon site (which will borrow from Editorial styles)
2. What we do for things like documentation, where Product and Editorial spacing could be interspersed
3. Vetting the Layout spacer values for Product, much like what we did with the component spacers 


## For Carbon site...
@joshblack and I applied Editorial styles for consistency:

![vertical_spacing_editorial](https://user-images.githubusercontent.com/43144260/48567847-b3f14380-e8c3-11e8-9961-6bf0492a6f1c.png)

Also, @eraymond25 made symbols for the various leadspaces at all breakpoints in Editorial and shared them:  https://ibm.box.com/s/uxru8x176r9i1fbnyrv8zcasw7ru9s0w

![screen shot 2018-11-15 at 10 51 20 am](https://user-images.githubusercontent.com/43144260/48568206-72ad6380-e8c4-11e8-87f7-677b42e7a9f7.png)

## For docs...
@joshblack feels that docs will need to be denser and have tighter vertical spacing; we haven't explored how Product and Editorial spacing scales will work together and this will become more of a priority after the v10 launch.

## Carbon Layout Spacers...
Just like with the Component Spacers, we're keeping the Carbon Layout Spacers as well, with one exception, we are adding an 80px spacer and instead of t-shirt sizes, we are using this convention:

Layout--01
Layout--02
Layout--03
etc.
