### ISSUE TITLE
Can't import Icon in Vuejs

### ISSUE THREAD

**Issue by eschao** [IBM/carbon-elements#482]
Following the guide to install **@carbon/icons-vue** with npm:
```shell 
npm install -S @carbon/icons-vue
```
and then using the second approach to import icon locally:
```js
import { Add16 } from '@carbon/icons-vue'
...
    components: {
        Add16,
    }
```
Unfortunately, I got the output from Vue console:
```
148:14-19 "export 'Add16' was not found in '@carbon/icons-vue'
```
Add of course, I can't see icon in my page.

What's wrong with my steps? 

Here is the part of my package.json:
```js
  "dependencies": {
    "@carbon/icons-vue": "^10.0.0",
    "carbon-components": "^8.16.8",
    "cron-parser": "^2.6.0",
    "cronstrue": "^1.57.0",
    "eslint-plugin-vue": "^4.7.1",
    "v-click-outside": "^1.0.4",
    "vue": "^2.5.2",
    "vue-awesome": "^2.3.4",
    "vue-resource": "^1.3.5",
    "vue-router": "^3.0.1",
    "vue-svg-sprite-loader": "^1.0.0",
    "vuex": "^3.0.1"
  },
````

**Comment by joshblack** [comment]
Hi @eschao! 👋 Unfortunately, the README is outdated. Since we have so many icons, you'll have to import icons by path while we figure out a way to offer a better development experience 😬 The [icons page here](https://carbon-elements.netlify.com/icons/examples/preview/) has an overview on how to get that path in the meantime.
