### ISSUE TITLE
Responsive spacing

### ISSUE THREAD

**Issue by photodow** [IBM/carbon-elements#74]
**The problem**
We've seen a need within the Digital Design System where adopters might want more content spacing on a large screen, but less on a smaller screen.

**The solution**
We thought we could contribute back the responsive [spacing classes](https://www.ibm.com/standards/web/code-guidelines/spacing-classes/) we've been using for a little time now in the Digital Design System as tokens.

Looking at your [_spacing.scss](https://github.com/IBM/carbon-elements/blob/master/packages/layout/scss/_spacing.scss) file we might be able to follow a similar pattern.

```sass
$responsive-spacing-scale: ( // we only have 3 at the moment
    2vw,
    5vw,
    10vw
);

@function responsive-spacing($step) {
    @return nth($responsive-spacing-scale, $step + 1);
}
```

**Alternative solution**
We could look at different names, but also if we wanted to add a little logic we could look into making use of the single `spacing()` function you already have in place.

```sass
@function spacing($step, $responsive) {
    @return nth(if($responsive, $responsive-spacing-scale, $spacing-scale), $step + 1);
}
```

**Additional context**
See bottom of Digital Design System's [spacing classes](https://www.ibm.com/standards/web/code-guidelines/spacing-classes/) page for documentation.

**Comment by joshblack** [comment]
cc @jeanservaas @aagonzales

**Comment by jeanservaas** [comment]
Yes! Any help exploring and pushing the spacing scale (fixed and fluid) forward would be greatly appreciated. As we talked about with @eraymond25 last week, we haven't done an audit yet of how layout spacers are working in product, so we're definitely behind you guys and borrowing heavily from your thinking at the moment. And since responsive spacing classes are more for digital lead spaces and stuff it would be great to fold in your work on that.
